In [ ]:
import numpy as np

# Example input: arrays of shape (n, 3)
A = np.random.rand(2, 3)  # 2 vectors, each of length 3
B = np.random.rand(2, 3)

print("A:\n",A,"\nB:\n",B)

# Compute W: elementwise dot products
W = np.einsum('ij,ij->i', A, B)  # Shape (10,)

# Convert to column vector of scalars (shape: (10, 1))
W = W[:, np.newaxis]

print("W:\n",W)

A:
 [[0.96662096 0.25569117 0.9402789 ]
 [0.32906926 0.77585783 0.35174708]] 
B:
 [[3.97263518e-01 1.66260113e-01 2.03313222e-04]
 [9.53619738e-01 9.95396283e-01 5.25851307e-01]]
W:
 [[0.42670566]
 [1.2710596 ]]
