In [5]:
import numpy as np

# Example input: arrays of shape (n, 3)
A = np.random.rand(2, 3)  # 2 vectors, each of length 3
B = np.random.rand(2, 3)

print("A:\n",A,"\nB:\n",B)

# Compute W: elementwise dot products
W = np.einsum('ij,ij->i', A, B)  # Shape (10,)

# Convert to column vector of scalars (shape: (10, 1))
W = W[:, np.newaxis]

print("W:\n",W)

A:
 [[0.16212207 0.44831797 0.98240301]
 [0.10242102 0.59571436 0.69417095]] 
B:
 [[0.76819939 0.38825451 0.54268418]
 [0.6289699  0.63088389 0.57744742]]
W:
 [[0.83173812]
 [0.84109356]]
